# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-02-20 12:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0005_auto_20170307_0657'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofileinfo',
            name='featured_skills',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
