# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-02-20 12:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0006_userprofileinfo_featured_skills'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofileinfo',
            old_name='featured_skills',
            new_name='name',
        ),
    ]
