# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-02-20 12:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0007_auto_20200220_1742'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofileinfo',
            old_name='name',
            new_name='featured_skills',
        ),
    ]
